---
# Supported annotations
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/ingress/annotations/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2-ingress
  namespace: app2-ingress
  annotations:
    cert-manager.io/cluster-issuer: "http-02-prod"
spec:
  ingressClassName: external-nginx
  rules:
    - host: app2-ingress.valerii-vasianovych.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app2-service
                port:
                  number: 3000
  tls:
    - hosts:
        - app2-ingress.valerii-vasianovych.site
      secretName: app2-ingress-tls